"""
Management command: python manage.py make_release [--full]

1. Cleans temporary/generated files from the project tree.
   --full  also removes collected static files (staticfiles/) and log files.

2. Creates a zip archive of the project, excluding runtime/sensitive paths.

3. Saves the archive to  <BASE_DIR>/VERSIONS/  with the name:
   {platform_name}_v{platform_version}_{YYYY.mm.dd}_{n}.zip
   where {n} increments automatically if a file with the same date already exists.
"""

import os
import re
import shutil
import zipfile
from datetime import date
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

# ── Paths excluded from the zip archive ──────────────────────────────────────
_EXCLUDE_DIRS = {
    'venv', '.venv', 'env',
    '__pycache__',
    '.git', '.github',
    'staticfiles',       # collected static — regenerated by collectstatic
    'VERSIONS',          # the output folder itself
    'certs',             # SSL certificates
    'node_modules',
}

_EXCLUDE_SUFFIXES = {
    '.pyc', '.pyo', '.pyd',
    '.log',
    '.db', '.sqlite3',
    '.zip',
    '.DS_Store',
}

_EXCLUDE_FILES = {
    '.env',
    'Thumbs.db',
}


class Command(BaseCommand):
    help = 'Clean the project tree and create a versioned zip archive in VERSIONS/'

    def add_arguments(self, parser):
        parser.add_argument(
            '--full',
            action='store_true',
            help='Also remove collected static files (staticfiles/) and log files.',
        )
        parser.add_argument(
            '--bump',
            choices=['patch', 'minor', 'major'],
            default='patch',
            help='Which semver part to increment in <BASE_DIR>/VERSION before packaging (default: patch).',
        )
        parser.add_argument(
            '--no-bump',
            action='store_true',
            help='Skip the version bump and package whatever is currently in <BASE_DIR>/VERSION.',
        )

    def handle(self, *args, **options):
        base_dir = Path(settings.BASE_DIR)
        full     = options['full']
        no_bump  = options['no_bump']
        bump     = options['bump']

        # ── 1. Clean ─────────────────────────────────────────────────────────
        self.stdout.write(self.style.MIGRATE_HEADING('=== Clean ==='))
        self._clean(base_dir, full=full)

        # ── 2. Bump version + determine archive name ─────────────────────────
        platform_name = self._get_platform_name()
        current_version = self._read_version_file(base_dir)
        if no_bump:
            platform_version = current_version
            self.stdout.write(self.style.WARNING(
                f'\n--no-bump set; packaging current version {platform_version} as-is.'
            ))
        else:
            platform_version = self._bump_version(current_version, bump)
            self._write_version_file(base_dir, platform_version)
            self.stdout.write(self.style.SUCCESS(
                f'\nVersion bumped: {current_version} → {platform_version} ({bump})'
            ))
        today = date.today().strftime('%Y.%m.%d')

        versions_dir = base_dir / 'VERSIONS'
        versions_dir.mkdir(exist_ok=True)

        n        = self._next_sequence(versions_dir, platform_name, platform_version, today)
        filename = f'{platform_name}_v{platform_version}_{today}_{n}.zip'
        out_path = versions_dir / filename

        # ── 3. Create zip ─────────────────────────────────────────────────────
        self.stdout.write(self.style.MIGRATE_HEADING('\n=== Archive ==='))
        self._create_zip(base_dir, out_path)

        self.stdout.write(self.style.SUCCESS(f'\nRelease created: VERSIONS/{filename}'))

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _clean(self, base_dir: Path, full: bool) -> None:
        removed_dirs  = 0
        removed_files = 0

        # Always remove __pycache__ and compiled Python files
        for root, dirs, files in os.walk(base_dir, topdown=True):
            root_path = Path(root)

            # Skip the VERSIONS folder entirely
            dirs[:] = [d for d in dirs if d != 'VERSIONS']

            # Remove __pycache__ directories
            if '__pycache__' in dirs:
                shutil.rmtree(root_path / '__pycache__', ignore_errors=True)
                dirs.remove('__pycache__')
                removed_dirs += 1

            # Remove .pyc / .pyo files
            for f in files:
                if Path(f).suffix in {'.pyc', '.pyo', '.pyd'}:
                    (root_path / f).unlink(missing_ok=True)
                    removed_files += 1

        self.stdout.write(f'  Removed {removed_dirs} __pycache__ dirs, {removed_files} compiled files.')

        if full:
            # Remove collected static files
            static_root = Path(getattr(settings, 'STATIC_ROOT', base_dir / 'staticfiles'))
            if static_root.exists():
                shutil.rmtree(static_root, ignore_errors=True)
                self.stdout.write(f'  Removed staticfiles/.')

            # Remove log files
            log_dir = base_dir / 'logs'
            if log_dir.exists():
                count = 0
                for log_file in log_dir.glob('*.log*'):
                    log_file.unlink(missing_ok=True)
                    count += 1
                self.stdout.write(f'  Removed {count} log file(s).')

    def _create_zip(self, base_dir: Path, out_path: Path) -> None:
        added = 0
        with zipfile.ZipFile(out_path, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
            for root, dirs, files in os.walk(base_dir, topdown=True):
                root_path = Path(root)

                # Prune excluded directories in-place (prevents descending into them)
                dirs[:] = [
                    d for d in dirs
                    if d not in _EXCLUDE_DIRS and not d.startswith('.')
                ]

                for filename in files:
                    file_path = root_path / filename

                    # Skip excluded suffixes and filenames
                    if (file_path.suffix.lower() in _EXCLUDE_SUFFIXES
                            or filename in _EXCLUDE_FILES
                            or filename.startswith('.')):
                        continue

                    # Archive path relative to base_dir's parent so the zip
                    # contains a single top-level folder named after the project.
                    arcname = file_path.relative_to(base_dir.parent)
                    zf.write(file_path, arcname)
                    added += 1

        size_mb = out_path.stat().st_size / 1024 / 1024
        self.stdout.write(f'  {added} files archived  ({size_mb:.1f} MB).')

    def _next_sequence(self, versions_dir: Path, name: str, version: str, today: str) -> int:
        """Return the next integer suffix so the filename is unique for today."""
        prefix   = f'{name}_v{version}_{today}_'
        existing = [
            f.name for f in versions_dir.glob(f'{prefix}*.zip')
        ]
        if not existing:
            return 1
        numbers = []
        for fname in existing:
            m = re.search(r'_(\d+)\.zip$', fname)
            if m:
                numbers.append(int(m.group(1)))
        return max(numbers, default=0) + 1

    def _get_platform_name(self) -> str:
        try:
            from apps.settings_app.branding import platform_name
            return platform_name()
        except Exception:
            return 'CYBERCavalry'

    def _get_platform_version(self) -> str:
        from django.conf import settings as _s
        return self._read_version_file(Path(_s.BASE_DIR))

    # ── VERSION file helpers ────────────────────────────────────────────────
    _VERSION_FILE = 'VERSION'
    _DEFAULT_VERSION = '1.0.0'

    def _read_version_file(self, base_dir: Path) -> str:
        """Read <BASE_DIR>/VERSION, falling back to '1.0.0' if missing/invalid."""
        p = base_dir / self._VERSION_FILE
        try:
            raw = p.read_text(encoding='utf-8').strip()
            if re.match(r'^\d+\.\d+\.\d+$', raw):
                return raw
        except OSError:
            pass
        return self._DEFAULT_VERSION

    def _write_version_file(self, base_dir: Path, version: str) -> None:
        """Write the version string (with trailing newline) to <BASE_DIR>/VERSION."""
        (base_dir / self._VERSION_FILE).write_text(version + '\n', encoding='utf-8')

    @staticmethod
    def _bump_version(version: str, part: str) -> str:
        """Return semver-bumped version. part ∈ {patch, minor, major}."""
        m = re.match(r'^(\d+)\.(\d+)\.(\d+)$', version)
        if not m:
            major, minor, patch = 1, 0, 0
        else:
            major, minor, patch = int(m.group(1)), int(m.group(2)), int(m.group(3))
        if part == 'major':
            major += 1; minor = 0; patch = 0
        elif part == 'minor':
            minor += 1; patch = 0
        else:  # patch
            patch += 1
        return f'{major}.{minor}.{patch}'
