# Generated by Django 4.2.16 on 2026-04-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0002_whitelistentry_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistentry',
            options={'ordering': ['-added_at']},
        ),
    ]
