# Generated by Django 4.2.16 on 2026-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_threat_intel_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='category',
            field=models.CharField(choices=[('ldap', 'LDAP'), ('api', 'API'), ('security', 'Security'), ('general', 'General'), ('threat_intel', 'Threat Intelligence')], default='general', max_length=20),
        ),
    ]
