# Generated by Django 4.2.16 on 2026-04-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_rename_auditlog_activitylog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='settings_app_auditlog',
        ),
    ]
