# Generated by Django 4.2.16 on 2026-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0013_backup_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='category',
            field=models.CharField(choices=[('ldap', 'LDAP'), ('api', 'API'), ('security', 'Security'), ('general', 'General'), ('threat_intel', 'Threat Intelligence'), ('password_policy', 'Password Policy'), ('backup', 'Backup')], default='general', max_length=20),
        ),
    ]
