# Generated by Django 4.2.16 on 2026-04-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('default_duration_hours', models.IntegerField(blank=True, help_text='Null = permanent', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Show in public API endpoints')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('prefix_length', models.IntegerField(default=32)),
                ('cidr', models.CharField(db_index=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import')], default='manual', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, help_text='Source IP of API reporter', null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blacklist.blacklistgroup')),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='blacklist_b_is_acti_9adcf0_idx'), models.Index(fields=['ip_address'], name='blacklist_b_ip_addr_d0c023_idx')],
                'unique_together': {('cidr', 'group')},
            },
        ),
    ]
