# Generated by Django 4.2.30 on 2026-08-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urllist', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='urlentry',
            new_name='urllist_url_is_acti_8c179d_idx',
            old_name='urllist_ur_is_acti_idx',
        ),
    ]
