# Generated by Django 4.2.16 on 2026-04-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashlist', '0002_hashentry_virustotal_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hashentry',
            new_name='hashlist_ha_is_acti_fe8d59_idx',
            old_name='hashlist_ha_is_acti_idx',
        ),
    ]
