# Generated by Django 4.2.16 on 2026-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashlist', '0003_rename_hashlist_ha_is_acti_idx_hashlist_ha_is_acti_fe8d59_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashentry',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned entries are exempt from automatic score-based deactivation'),
        ),
    ]
